Implement Gulp plugin for TestCafe
DevExpress/gulp-testcafe pull request #1
Opened 2016-09-19 12:44 UTC by inikulin

\cc @VasilyStrelyaev @AndreyBelym @AlexanderMoskovkin

2016-09-19 13:35 UTC, VasilyStrelyaev commented on README.md
> +Allows you to manually select which tests should be run.
Let's add more references to **Programming interface** from here.

Probably, add a section after the descriptions like

```
*Details*: (link)
```

2016-09-19 13:38 UTC, VasilyStrelyaev commented on README.md
> +Allows you to manually select which tests should be run.
In this case,

```
*Details*: [runner.filter](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#filter)
```

2016-09-19 13:45 UTC, VasilyStrelyaev commented on README.md
> +Specifies the amount of time, in milliseconds, within which selectors make attempts to obtain a node to be returned.
Maybe add a link to selectors?

```
Specifies the amount of time, in milliseconds, within which [selectors](https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors.html) make attempts to obtain a node to be returned.
```

2016-09-19 13:48 UTC, VasilyStrelyaev commented on README.md
> +Specifies if screenshots should be taken automatically whenever a test fails.
Let's give a link to docs... or just add that you should specify the path.

```
Specifies if screenshots should be taken automatically whenever a test fails. Requires that the [screenshotsPath](#screenshotsPath) is set.
```

2016-09-19 13:50 UTC, VasilyStrelyaev requested changes
\r-

2016-09-19 14:54 UTC, AndreyBelym commented on test/manual/mocha-test.js
> +it('Should pass', function () {
Everything is fine, except that I didn't get the purpose of this file (and `unit` task in `Gulpfile`), sorry.

2016-09-19 15:18 UTC, inikulin commented on test/manual/mocha-test.js
> +it('Should pass', function () {
It's for the manual testing as directory title suggests

2016-09-19 16:19 UTC, AlexanderMoskovkin approved these changes
lgtm

2016-09-20 08:47 UTC, AndreyBelym approved these changes
lgtm

2016-09-20 10:04 UTC, inikulin commented
FPR

2016-09-20 10:24 UTC, VasilyStrelyaev approved these changes
lgtm

2016-09-20 10:24 UTC, merged